name: Deploy React App to cPanel

on:
  push:
    branches:
      - main  # Jab bhi main branch pe push hoga, deploy karega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.CPANEL_HOST}}
          username: ${{secrets.CPANEL.USERNAME}}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: dist/
          server-dir: /public_html/react_app/
